"""One-time interactive Schwab OAuth authorization helper.

Run once (and again only if the refresh token has gone stale) to seed the macOS
Keychain with the access/refresh tokens the MCP server reads at runtime:

    export SCHWAB_CLIENT_ID=...
    export SCHWAB_CLIENT_SECRET=...
    openssl req -x509 -newkey rsa:2048 -keyout /tmp/key.pem -out /tmp/cert.pem \
        -days 1 -nodes -subj '/CN=127.0.0.1'
    uv run python scripts/authorize.py

The flow opens a browser to Schwab's authorize endpoint, captures the redirect
on a single-use localhost HTTPS server, exchanges the returned code for tokens
(via the project's own ``auth`` module — the only place that POSTs to Schwab),
and stores them in the Keychain. macOS prompts for Keychain access on first
store; approve it.

This script makes no direct HTTP calls itself, never writes tokens or secrets
to disk, and never logs or echoes a secret value. It is run from the repo root;
``scripts/`` is not part of the installed package, so the project module is
imported by name (``from schwab_readonly_mcp import auth``) off the path that
``uv run`` puts on ``sys.path``.
"""

import asyncio
import http.server
import os
import secrets
import ssl
import sys
import webbrowser
from urllib.parse import parse_qs, urlencode, urlsplit

from schwab_readonly_mcp import auth

AUTHORIZE_URL = "https://api.schwabapi.com/v1/oauth/authorize"

# Must byte-match the callback URL registered in the Schwab Developer Portal
# exactly — Schwab does an exact-string comparison, so NO trailing slash.
REDIRECT_URI = "https://127.0.0.1:8182"
HOST = "127.0.0.1"
PORT = 8182

# Pre-generated by the operator (see module docstring / README). Kept off the
# package and out of git (.gitignore excludes /tmp/*.pem and *.pem).
CERT_FILE = "/tmp/cert.pem"
KEY_FILE = "/tmp/key.pem"

# Cap the smoke-test dump so a full portfolio doesn't scroll forever. Tokens are
# never part of that payload, but truncation also keeps any stray field short.
SMOKE_TEST_MAX_CHARS = 2000


def build_authorize_url(client_id: str, redirect_uri: str, state: str) -> str:
    """Build the Schwab authorize URL with the CSRF ``state`` parameter.

    Response type is the OAuth ``code`` flow; ``state`` is echoed back on the
    redirect and verified to defend against CSRF / cross-session callbacks.
    """
    query = urlencode(
        {
            "response_type": "code",
            "client_id": client_id,
            "redirect_uri": redirect_uri,
            "state": state,
        }
    )
    return f"{AUTHORIZE_URL}?{query}"


def parse_callback(raw_path: str, expected_state: str) -> str:
    """Extract the authorization ``code`` from the redirect path.

    Validates the echoed ``state`` against ``expected_state`` (constant-time)
    and surfaces a Schwab-reported ``error`` param as a ``RuntimeError``. Raises
    on a missing/blank/mismatched ``state`` or a missing ``code`` so a malformed
    or forged callback can never proceed to a token exchange.
    """
    query = parse_qs(urlsplit(raw_path).query)
    returned_state = (query.get("state") or [""])[0]
    # Constant-time compare; reject a missing/blank state outright (an empty
    # expected_state must never be satisfiable).
    if not returned_state or not secrets.compare_digest(returned_state, expected_state):
        raise RuntimeError("OAuth state mismatch: possible CSRF, refusing callback")
    error = (query.get("error") or [""])[0]
    if error:
        raise RuntimeError(f"Schwab returned an OAuth error: {error}")
    code = (query.get("code") or [""])[0]
    if not code:
        raise RuntimeError("OAuth callback missing authorization code")
    return code


def truncate_for_display(text: str, max_chars: int = SMOKE_TEST_MAX_CHARS) -> str:
    """Truncate a display string, appending an explicit elision marker."""
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + f"\n... [truncated, {len(text)} chars total]"


def _require_credentials() -> tuple[str, str]:
    # Mirror server._credentials(): a missing/empty value is an operator-config
    # error → clear message, and NEVER echo either value (only their absence).
    client_id = os.environ.get("SCHWAB_CLIENT_ID")
    client_secret = os.environ.get("SCHWAB_CLIENT_SECRET")
    if not client_id or not client_secret:
        raise SystemExit(
            "error: SCHWAB_CLIENT_ID and SCHWAB_CLIENT_SECRET must be set "
            "in the environment (export them from the Schwab Developer Portal)."
        )
    return client_id, client_secret


def _require_cert() -> ssl.SSLContext:
    # Schwab requires an HTTPS callback. Fail with an actionable message — incl.
    # the exact openssl command — rather than a raw ssl/FileNotFoundError.
    if not os.path.exists(CERT_FILE) or not os.path.exists(KEY_FILE):
        raise SystemExit(
            f"error: missing TLS cert ({CERT_FILE}) or key ({KEY_FILE}).\n"
            "Generate a one-day self-signed localhost cert first:\n\n"
            "  openssl req -x509 -newkey rsa:2048 -keyout /tmp/key.pem "
            "-out /tmp/cert.pem -days 1 -nodes -subj '/CN=127.0.0.1'\n"
        )
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
    return context


class _CallbackHandler(http.server.BaseHTTPRequestHandler):
    # Single-use callback handler. Stashes the raw request path on the server so
    # the main thread can parse it after serve_forever-equivalent shutdown.
    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
        self.server.callback_path = self.path  # type: ignore[attr-defined]
        body = (
            b"<html><body><h2>Authorization received.</h2>"
            b"<p>You can close this tab and return to the terminal.</p>"
            b"</body></html>"
        )
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args: object) -> None:
        # Silence the default stderr access log — the request path can carry the
        # authorization code, which must never be logged.
        return


def _capture_callback(context: ssl.SSLContext) -> str:
    """Serve exactly one HTTPS request on 127.0.0.1:8182 and return its path.

    Binds to loopback only, wraps the socket in TLS, handles a single callback,
    then shuts down. Returns the raw request path (with query string).
    """
    httpd = http.server.HTTPServer((HOST, PORT), _CallbackHandler)
    httpd.callback_path = None  # type: ignore[attr-defined]
    httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
    try:
        # Exactly one callback, then we stop. No persistent listener.
        httpd.handle_request()
    finally:
        httpd.server_close()
    path = httpd.callback_path  # type: ignore[attr-defined]
    if not path:
        raise RuntimeError("no OAuth callback received")
    return path


def _smoke_test_command() -> str:
    # The one-liner the operator runs next: fetch a (refreshed) access token,
    # list accounts, and print a TRUNCATED dump. Never prints tokens.
    return (
        "uv run python -c '"
        "import asyncio, json; "
        "from schwab_readonly_mcp import auth; "
        "from schwab_readonly_mcp.client import SchwabClient; "
        "import os; "
        'cid=os.environ["SCHWAB_CLIENT_ID"]; csec=os.environ["SCHWAB_CLIENT_SECRET"]; '
        "tok=asyncio.run(auth.get_access_token(cid, csec)); "
        "data=asyncio.run(SchwabClient(tok).list_accounts()); "
        "s=json.dumps(data, indent=2); "
        'print(s[:2000] + ("\\n... [truncated]" if len(s) > 2000 else ""))'
        "'"
    )


def main() -> None:
    client_id, client_secret = _require_credentials()
    context = _require_cert()
    state = secrets.token_urlsafe(32)

    url = build_authorize_url(client_id, REDIRECT_URI, state)
    print(f"Opening browser to authorize at {AUTHORIZE_URL} ...")
    print("If the browser does not open, paste this URL manually:\n")
    print(f"  {url}\n")
    webbrowser.open(url)

    print(f"Waiting for the Schwab redirect on {REDIRECT_URI} ...")
    raw_path = _capture_callback(context)
    code = parse_callback(raw_path, state)

    print("Authorization code received; exchanging for tokens ...")
    tokens = asyncio.run(
        auth.exchange_code_for_tokens(code, client_id, client_secret, REDIRECT_URI)
    )
    # macOS prompts for Keychain access here on first store — approve it.
    auth.store_tokens(tokens)

    print(f"\nSuccess. Tokens stored in the macOS Keychain (service '{auth.SERVICE}').")
    print("\nSmoke-test it (prints a truncated accounts dump, never tokens):\n")
    print(f"  {_smoke_test_command()}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
